Repository devvsakib/hackerboi, pull requests merged in 2022-10, with the labels that each got.

#22 update readme.md
  README.md
Labels: documentation, hacktoberfest

#31 Title color in Contributors page
  css/styles.css
Labels: hacktoberfest

#32 Create FAQ's
  FAQ's
Labels: documentation, hacktoberfest

#41 Update index.html
  index.html
Labels: good first issue, hacktoberfest
